
name: crownstonehub-ilhan-test
version: git
summary: greeting .
description: |
 hello + name greeting
confinement: devmode
#base: core18

parts:
  crownstonehub-ilhan-test:
    plugin: nodejs
    source: .

apps:
  hello:
    command: hello
    
